-- ChorePal Database Schema
-- Primary Tables for User Management, Chore Workflow, and AI Verification
--
-- This reflects the live database as of 2026-10-08 (confirmed via
-- `supabase db dump`), not just what migrations/earlier drafts assumed.

-- 1. Users Table (Role-based: Parent/Child)
CREATE TABLE public.users (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  family_id UUID, -- Household this user belongs to (no families table - a shared value, not an FK)
  role TEXT CHECK (role IN ('parent', 'child')),
  username TEXT UNIQUE NOT NULL,
  display_name TEXT,
  avatar_url TEXT,
  secret_code TEXT UNIQUE, -- the household's persistent join code
  current_balance NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Chores Table (Chore definition, assignment, and approval)
CREATE TABLE public.chores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by UUID REFERENCES public.users(id) NOT NULL,
  assigned_to UUID REFERENCES public.users(id),
  approved_by UUID REFERENCES public.users(id),
  title TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'todo',
  target_label TEXT, -- What the AI is looking for
  ai_verified BOOLEAN DEFAULT false,
  reward_amount NUMERIC DEFAULT 0,
  due_date TIMESTAMP WITH TIME ZONE,
  submitted_at TIMESTAMP WITH TIME ZONE,
  approved_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Chore Analysis Table (one row per submission attempt: before/after
-- photos and the AI's verdict for that attempt)
CREATE TABLE public.chore_analysis (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  chore_id BIGINT REFERENCES public.chores(id) ON DELETE CASCADE,
  before_image_key TEXT, -- S3 Bucket Key
  after_image_key TEXT, -- S3 Bucket Key
  ai_detected_label TEXT,
  ai_confidence_score NUMERIC,
  ai_feedback TEXT,
  needs_revision BOOLEAN DEFAULT false,
  attempt_number INTEGER DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Rewards Table (Reward Catalog)
CREATE TABLE public.rewards (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_by UUID REFERENCES public.users(id) DEFAULT auth.uid() NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  point_cost NUMERIC,
  category TEXT,
  archived BOOLEAN DEFAULT false NOT NULL, -- kept instead of deleted so redemption history keeps its name
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Transactions Table (Virtual Wallet Ledger - credits from approved
-- chores, debits from redeemed rewards)
CREATE TABLE public.transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.users(id) NOT NULL,
  chore_id BIGINT REFERENCES public.chores(id),
  reward_id UUID REFERENCES public.rewards(id),
  amount NUMERIC DEFAULT 0,
  type TEXT, -- 'credit' or 'debit'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
