-- ChorePal Database Schema
-- Primary Tables for User Management, Chore Workflow, and AI Verification

-- 1. Families Table (Household grouping)
CREATE TABLE public.families (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Users Table (Role-based: Parent/Child)
CREATE TABLE public.users (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  family_id UUID REFERENCES public.families(id), -- Household this user belongs to
  role TEXT CHECK (role IN ('parent', 'child')),
  username TEXT UNIQUE NOT NULL,
  display_name TEXT,
  current_balance NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Invites Table (Single-use codes a parent generates per person joining)
CREATE TABLE public.invites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id UUID REFERENCES public.families(id) NOT NULL,
  code TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Chores Table (Chore definition and photo evidence)
CREATE TABLE public.chores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by UUID REFERENCES public.users(id) NOT NULL,
  assigned_to UUID REFERENCES public.users(id),
  title TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'pending',
  after_image_key TEXT, -- S3 Bucket Key for photo proof
  target_label TEXT, -- What the AI is looking for
  reward_amount NUMERIC DEFAULT 0,
  due_date TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Transactions Table (Virtual Wallet Ledger)
CREATE TABLE public.transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.users(id),
  chore_id BIGINT REFERENCES public.chores(id),
  amount NUMERIC NOT NULL,
  type TEXT, -- 'credit' or 'debit'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Rewards Table (Reward Catalog)
CREATE TABLE public.rewards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by UUID REFERENCES public.users(id) NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  point_cost NUMERIC DEFAULT 0,
  category TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);