-- Base tables. These were originally created by hand on the hosted project
-- rather than through a migration, which is why every later migration here
-- is an ALTER assuming they already exist - this one makes that explicit
-- and lets a fresh/local environment bootstrap from scratch.

-- 1. Users Table (Role-based: Parent/Child)
CREATE TABLE public.users (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  account_owner_id UUID REFERENCES public.users(id), -- Linked to Parent
  role TEXT CHECK (role IN ('parent', 'child')),
  username TEXT UNIQUE NOT NULL,
  secret_code TEXT UNIQUE,
  current_balance NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Chores Table (Chore definition and photo evidence)
CREATE TABLE public.chores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by UUID REFERENCES public.users(id) NOT NULL,
  assigned_to UUID REFERENCES public.users(id),
  title TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'pending',
  after_image_key TEXT, -- S3 Bucket Key for photo proof
  target_label TEXT, -- What the AI is looking for
  reward_amount NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Transactions Table (Virtual Wallet Ledger)
CREATE TABLE public.transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.users(id),
  chore_id BIGINT REFERENCES public.chores(id),
  amount NUMERIC NOT NULL,
  type TEXT, -- 'credit' or 'debit'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
